version: '3.7'

services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        hostname: mariadb
        restart: unless-stopped
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: password
        # Copy-pasted from https://github.com/docker-library/mariadb/issues/94
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "--silent"]
    keycloak:
        image: quay.io/keycloak/keycloak:legacy
        container_name: keycloak
        hostname: keycloak
        restart: unless-stopped
        environment:
            DB_VENDOR: mariadb
            DB_ADDR: mariadb
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_PASSWORD: password
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: password
            JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
            # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
            #JDBC_PARAMS: "ssl=true"
        ports:
            - "8880:8080"
        depends_on:
            - mariadb

volumes:
    mysql_data:
        driver: local
